name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies and Test
        run: |
          pip install -r app/requirements.txt flake8
          flake8 app/app.py --count --select=E9,F63,F7,F82 --show-source --statistics
          python3 test_app.py

  build-and-deploy:
    needs: test # This ensures we don't build broken code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag
        run: |
          docker build -t task-telemetry-api ./app
          docker tag task-telemetry-api:latest ${{ steps.login-ecr.outputs.registry }}/task-telemetry-api:latest

      - name: DevSecOps - Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/task-telemetry-api:latest'
          format: 'table'
          exit-code: '1' # Fails the build if high-risk vulnerabilities exist
          severity: 'CRITICAL,HIGH'

      - name: Push to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/task-telemetry-api:latest